version: "3.7"
services:
  app-db:
    container_name: app-elo-shot-counting-db
    image: mysql
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Uncomment to allow empty root password
      # MYSQL_RANDOM_ROOT_PASSWORD: "yes"  # Uncomment to generate a random root password

    volumes:
      - app-elo-shot-counting:/var/lib/mysql
volumes:
  app-elo-shot-counting:
